---
- name: install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - zsh
    - git

- name: install prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto
  sudo: false

- name: get rid of existing ~/.zshrc
  file: path=~/.zshrc state=absent
  sudo: false

- name: symlink new dotfiles
  file: src=~/.zprezto/runcoms/{{ item }} dest=~/.{{ item }}
        state=link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
  sudo: false

- name: switch to Zsh
  user: name={{ prezto_user }} shell=/usr/bin/zsh
  sudo: True
